server:
  port: 7000
  servlet:
    context-path: /rabbitmq
spring:
  rabbitmq:
    host: 47.104.237.108
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true  #发送确认
    publisher-returns: true  #发送回调
    listener:
      simple:
        acknowledge-mode: manual  #消费手动确认
        prefetch: 100
  mail:
    host: smtp.163.com
    username: 18621142249@163.com
    password: 123456wangzai
    from: 18621142249@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://47.104.237.108:3306/springboot
    username: root
    password: hyn123!@#
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver