server:
  port: 8083
spring:
  # redis连接配置
  redis:
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
      # 获取失败 最大重定向次数
      max-redirects: 3
    # lettuce连接池配置:
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 300
        # 连接池中的最小空闲连接 默认0
        min-idle: 5
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 600
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: 3000
      shutdown-timeout: 1000
    # 连接超时时间
    timeout: 20000
    # 支持16个数据库（相当于不同用户）可以使不同的应用程序数据彼此分开同时又存储在相同的实例上
    database: 0

